---
deployment:
  tasks:
    - export DEPLOYPATH=/home/garrettw/public_html/
    - /repositories/Commissioner/ -R html $DEPLOYPATH
    - /repositories/Commissioner/ -R css $DEPLOYPATH
    - /repositories/Commissioner/ -R images $DEPLOYPATH
